#!/bin/bash

#
# Copyright (C) 2016 Intel Corporation
#
# Author: Todor Minchev <todor.minchev@linux.intel.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, or (at your option) any later version, as published by
# the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#

#read proxy && port && type from environment if they are set
if [ ! -z "$PROXY" ] && [ ! -z "$PORT" ] && [ ! -z "$PROXY_TYPE" ]; then
 sed -i 's/proxy.mine.com/'$PROXY'/g' /etc/redsocks.conf
 sed -i '/local_port = 1080/!s/port = 1080/port = '$PORT'/g' /etc/redsocks.conf
 sed -i 's/socks5/'$PROXY_TYPE'/g' /etc/redsocks.conf
fi;

#Docker stop(SIGTERM) handler
redsocks_handler() {
  /etc/init.d/redsocks stop
  exit 143;
}

/etc/init.d/redsocks start

trap 'redsocks_handler' SIGTERM

#wait for redsocks to stop and exit
while true
do
  tail -f /dev/null & wait ${!}
done
